motto: Ricerca e Innovazione per la prevenzione dei rischi naturali.
mails:
  info: info@milegoalterritorio.it
socials:
  instagram:
    icon: fab fa-instagram
    link: https://www.instagram.com/milego_al_territorio/
  linkedin:
    icon: fab fa-linkedin
    link: https://www.linkedin.com/company/mi-lego-al-territorio/
  twitter:
    icon: fab fa-twitter-square
    link: https://twitter.com/lego_polito
