motto: Serious games and multimedia per la prevenzione dei rischi naturali
mails:
  info: info@milegoalterritorio.it
socials:
  instagram:
    icon: fab fa-instagram
    link: https://www.instagram.com/milego_al_territorio/
  facebook:
    icon: fab fa-facebook-square
    link: https://www.facebook.com/milegoalterritorio/
  twitter:
    icon: fab fa-twitter-square
    link: https://twitter.com/lego_polito
  linkedin:
    icon: fab fa-linkedin
    link: https://www.linkedin.com/company/mi-lego-al-territorio/
shortName: 'MLAT'
backgroundColor: '#FFFFFF'
themeColor: '#f8b10b'
