# Netlify CMS configuration

backend:
  name: git-gateway
  branch: master # Branch to update

publish_mode: editorial_workflow

local_backend: true

media_folder: assets/images # Media files will be stored in the repo under assets/images

site_url: https://determined-aryabhata-518306.netlify.app/

logo_url: https://determined-aryabhata-518306.netlify.app/logo.svg

locale: it

collections:
  - name: general
    label: Generale
    description: Configurazione elementi particolari
    files:
      - label: Chi siamo
        name: about
        file: content/_index.md
        fields:
          - label: Chi siamo
            name: body
            widget: markdown
      - label: Motto e socials
        name: params
        file: config/_default/params.yaml
        fields:
          - label: Motto
            name: motto
            widget: string
          - label: Link social
            name: socials
            widget: list
            fields:
              - label: classe CSS icona
                name: icon
                widget: string
              - label: Link alla pagina social
                name: link
                widget: string
  - name: eventi
    label: Eventi
    folder: content/eventi
    create: true
    slug: '{{slug}}'
    description: Gli eventi del team
    preview_path: eventi
    filter:
      field: showCMS
      value: true
    fields:
      - label: Titolo
        name: title
        widget: string
        required: true
      - label: Luogo
        name: place
        widget: string
        required: true
      - label: Data
        name: date
        hint: La data dell'evento
        widget: datetime
        format: YYYY-MM-DD
        timeFormat: false
        required: true
      - label: Foto
        name: imgPath
        widget: image
        allow_multiple: false
        required: true
      - label: Descrizione
        name: body
        widget: markdown
        required: true
      - label: Mostra nel CMS
        name: showCMS
        widget: hidden
        default: true
  - name: partners
    label: Partners
    folder: content/partners
    create: true
    slug: '{{slug}}'
    description: I partners del team
    preview_path: partners
    filter:
      field: showCMS
      value: true
    fields:
      - label: Nome
        name: title
        widget: string
        required: true
      - label: Link
        name: link
        widget: string
        required: true
        pattern:
          [
            'https?:\/\/www\.[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*)',
            Non è un link,
          ]
      - label: Logo
        name: imgPath
        widget: image
        allow_multiple: false
        required: true
      - label: Mostra nel CMS
        name: showCMS
        widget: hidden
        default: true
  - name: team
    label: Team
    folder: content/team
    create: true
    slug: '{{slug}}'
    description: Le aree del team
    preview_path: team
    filter:
      field: showCMS
      value: true
    fields:
      - label: Nome team
        name: title
        widget: string
        required: true
      - label: Icona
        name: icon
        hint: classe css dell'icona
        widget: string
        required: true
      - label: Membri
        name: members
        widget: list
        fields:
          - label: Nome
            name: name
            widget: string
          - label: Link
            name: link
            widget: string
            pattern:
              [
                'https?:\/\/www\.[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*)',
                Non è un link,
              ]
        required: true
      - label: Mostra nel CMS
        name: showCMS
        widget: hidden
        default: true
  - name: education
    label: Didattica
    folder: content/didattica
    create: true
    slug: '{{slug}}'
    description: L'offerta didattica del team
    preview_path: didattica
    filter:
      field: showCMS
      value: true
    fields:
      - label: Nome attività
        name: title
        widget: string
        required: true
      - label: Area
        name: area
        hint: sismico/idraulico/...
        widget: string
        required: true
      - label: Numero dello step
        name: step
        widget: number
        min: 1
        valueType: int
        required: true
      - label: Durata dell'attività (minuti)
        name: min
        widget: number
        min: 1
        valueType: int
        required: true
      - label: Icona
        name: icon
        hint: classe css dell'icona
        widget: string
        required: true
      - label: Descrizione
        name: body
        widget: markdown
        required: true
      - label: Mostra nel CMS
        name: showCMS
        widget: hidden
        default: true
